### PR TITLE
Facebook authentication

### LINKED ISSUE #202: passport facebook (facebook api v2 & email permission disallowed)
Facebook API v2 no longer returns username, hence on FacebookStrategy callback we'll get undefined for profile.username.
Currently I'm using the below in `config/strategies/facebook.js` as my workaround. 
line 32: `username: profile.username || profile.id `

Another thing is when user chose not to allow the access of email from Facebook there'll be a small error which causes the app to skip saving/updating the user.
My workaround in `config/strategies/facebook.js` 
line 31: `email: (profile.emails)? profile.emails[0].value: ''`

### LINKED ISSUE #697: Facebook Login is not Working
The Facebook Login is not working and it does not throw any error in the console or web console.
The Facebook redirect works, but then in the application nothing is happening.
I have configured the App_id and secret. What's missing?

### PR DESCRIPTION
**Pull request by rhutchison**
Closes #202, and closes #697 - if user does not authorize email scope, email will not be mapped.  Username will be generated from first initial of first name and last name.

.jshint latedef set to nofunc.

### CODE REVIEW

**Comment by rhutchison** [comment]
I have tested these changes but need additional eyes.  If anyone is using facebook strategy please weigh in.

@simison @mleanos @codydaig @lirantal @ilanbiala @jcaspain @benmartin

File: modules/users/server/config/strategies/facebook.js [hunk 1]
```diff
@@ -36,6 +37,18 @@ module.exports = function (config) {
...
+      function generateUsername(profile) {
+        var username = '';
+
+        if (profile.emails) {
+          username = profile.emails[0].value.split('@')[0];
+        } else if (profile.name) {
+          username = profile.name.givenName[0] + profile.name.familyName;
+        }
+
+        return username.toLowerCase() || undefined;
```
Comment (lirantal) [inline modules/users/server/config/strategies/facebook.js]: What happens if on 45 or 47 the username field:
1. does not exist? meaning it's empty for some reason...
2. does not fit to go through validation? for example, it's length is too short/long or uses special UTF8 chars
3. already matches an existing username and then we'll fail on duplicate usernames

If we end up returning undefined, how would the call later to saveOauthUserProfile behave?

Comment (lirantal) [inline modules/users/server/config/strategies/facebook.js]: Also, take a look at https://github.com/meanjs/mean/blob/3064b2882048beebf5ff6fc9c3f9599a5650c764/modules/users/server/controllers/users/users.authentication.server.controller.js#L155 looks like it's already trying to figure out a username for the user.

Comment (rhutchison) [inline modules/users/server/config/strategies/facebook.js]: I saw this, but it does not handle it as nicely.  If there is no username, the app will not create a user, takes you to the login page.  Email is not required and if you reject access to email, then the current implementation does not work.  The case above is much more forgiving.  profile.name will always be returned, because that is the absolute minimum when authenticating with facebook.

**Comment by mleanos** [comment]
I've tested this, and it works for me; after updating my local env config to the correct fb callbackURL... `callbackURL: '/api/auth/facebook/callback'`

I still don't fully understand the implementation here though. I'll go through it thoroughly.

**Comment by lirantal** [comment]
Great, merging.
Thanks @rhutchison!
